### ISSUE TITLE
[bug]: `get`: The database (default) does not exist for project

### ISSUE THREAD

**Issue by dmustafic-datafin** [unytics/bigfunctions#107]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

The get function can not be executed after being deployed to the cloud. This is a log item from Cloud Run. 

debug_error_string = "UNKNOWN:Error received from peer ipv4:172.253.120.95:443 {created_time:"2023-05-29T13:08:01.432297163+00:00", grpc_status:5, grpc_message:"The database (default) does not exist for project bigquery-310412 Please visit https://console.cloud.google.com/datastore/setup?project=bigquery-310412 to add a Cloud Datastore or Cloud Firestore database.

**Comment by unytics** [comment]
Hi, 

Thanks for creating this issue.

I am using firestore in datastore mode for quota management. 

But this seems to complexify the deployment for people in their GCP project:
- deployer needs to have enabled firestore
- deployer needs to have his firestore in datastore mode.
- This is impossible to do if the deployer is already using firestore in native mode...
- service account used in the function needs to have the permission to write to firestore

That's why I am considering removing quota management by default.
**What do you think?**

What's more, I am not very happy with the scalability of how quota management is done for now. I am considering changing that in the future..

**Comment by dmustafic-datafin** [comment]
I would rather not have quota management than enable additional services.

In my case, firestore will be just another thing to worry about. And to be honest - a dealbreaker.

**Comment by unytics** [comment]
Sounds good. 
I will add an option to choose the quota manager backend (with none by default). 

So it should work for you. 

I'll let you know.

**Comment by unytics** [comment]
@dmustafic-datafin I push to main branch the updates.
Can you tell me if it works for you?

Here is the commit: 
https://github.com/unytics/bigfunctions/commit/5f72e804c53fe40d4d09e1651b8164e51cfb4d97

**Comment by dmustafic-datafin** [comment]
Hey, I pulled the commit, reinstall the function and now I get this:
![image](https://github.com/unytics/bigfunctions/assets/89752657/66c24791-cc0c-4741-a2b1-0312d7fd43c6)

**Comment by unytics** [comment]
Sorry. 
Can you repull and retry please?

**Comment by dmustafic-datafin** [comment]
bq function seems to be deployed correctly:

![image](https://github.com/unytics/bigfunctions/assets/89752657/c590cee3-099b-40bb-9ac2-1d9c91a74542)

**Comment by unytics** [comment]
You can change quota or disable them in the yaml of the function before deploying it. 

Now, as you don't use Firestore, the only quota that is taken into consideration is the number of rows per query.

**Comment by unytics** [comment]
For instance in geocode function you have: 

![image](https://github.com/unytics/bigfunctions/assets/111615732/c8f44299-4dcc-40b0-abac-b2f3c45609e1)


If you deploy with this config, users can call it on table of 10 rows maximum.  

Remove the quotas entries in this yaml before redeploying

**Comment by unytics** [comment]
The email address given in error is configured in your config.yaml at field quota_contact

**Comment by unytics** [comment]
Simply remove max_rows_per_query from the yaml file where you don't want it to be applied and redeploy the function of the yaml file. 

It does nothing if you put it in config.yaml.

**Comment by dmustafic-datafin** [comment]
That's it. After I changed max_rows_per_query in get.yaml everything is working fine. Thank you so much for your help!
