### ISSUE TITLE
[bug]: `explore_column `: can't make visualization work

### ISSUE THREAD

**Issue by amirali-shfz** [unytics/bigfunctions#131]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

not sure if I'm calling the function correctly, but none of the explore calls create visualizations. Here's what I see when I run ```call bigfunctions.us.explore_column("bigfunctions.us.natality.weight_pounds");
select html from bigfunction_result;```
<img width="1151" alt="image" src="https://github.com/unytics/bigfunctions/assets/25187424/9ed6718e-9452-49ad-b4db-42a67db0808f">
<img width="506" alt="image" src="https://github.com/unytics/bigfunctions/assets/25187424/83d86ac0-1628-46e8-af16-a2d902ec9b78">

When I put html in jsfiddle, I see this:
<img width="379" alt="image" src="https://github.com/unytics/bigfunctions/assets/25187424/e6cc886f-14ff-4bb8-8f78-a887cfac76df">

I asked chatgpt (lol) to fix the value and here's what I got.
old html:
```

                    <div class=""container"">
  <div class=""box"">
    <p class=""is-size-4 mb-6 mt-4"">Column <code>weight_pounds</code> <code>FLOAT64</code></p>
      <div class=""columns"">
        <div class=""column is-one-quarter"">
          <table class=""table is-narrow"">
            
              <tr><th class=""has-text-weight-bold"">min           </th><td>0.50044933474</td></tr>
              <tr><th class=""has-text-weight-bold"">mean          </th><td>7.312606681578967</td></tr>
              <tr><th class=""has-text-weight-bold"">max           </th><td>18.0007436923</td></tr>
            
            
              <tr><th class=""has-text-weight-bold"">distinct_count</th><td>5,727</td></tr>
              
            
            <tr><th class=""has-text-weight-bold"">missing_count </th><td >19,983</td></tr>
            
              <tr><th class=""has-text-weight-bold"">missing_ratio </th><td class=""has-background-danger-light"">0.2 %</td></tr>
            
            <tr><th class=""has-text-weight-bold"">row_count     </th><td>12,978,619</td></tr>
          </table>
        </div>
        <div class=""column"">
          
  <div><canvas id=""e6537ea7-1f58-4ba7-ad17-769ce9160ab7""></canvas></div>
  <script>
    (function() {
      new Chart(
        document.getElementById('e6537ea7-1f58-4ba7-ad17-769ce9160ab7'),
        {
            type: 'bar',
            data: {
              labels: [""[0.5, 2.25["",""[2.25, 4["",""[4, 5.75["",""[5.75, 7.5["",""[7.5, 9.25["",""[9.25, 11["",""[11, 12.75["",""[12.75, 14.5["",""[14.5, 16.25["",""[16.25, 18]""],
              datasets: [{
                label: 'value_count',
                data: [84161,186850,976204,5885362,5132205,668553,24143,950,126,82],
                borderColor: 'rgb(64, 81, 181)',
                backgroundColor: 'rgb(64, 81, 181)',
              }]
            },
            options: {}
          }
      );
    })();
  </script>

        </div>
      </div>
  </div>
</div>

```
new html
```
<div class="container">
  <div class="box">
    <p class="is-size-4 mb-6 mt-4">Column <code>weight_pounds</code> <code>FLOAT64</code></p>
    <div class="columns">
      <div class="column is-one-quarter">
        <table class="table is-narrow">
          <tr><th class="has-text-weight-bold">min           </th><td>0.50044933474</td></tr>
          <tr><th class="has-text-weight-bold">mean          </th><td>7.312606681578967</td></tr>
          <tr><th class="has-text-weight-bold">max           </th><td>18.0007436923</td></tr>
          <tr><th class="has-text-weight-bold">distinct_count</th><td>5,727</td></tr>
          <tr><th class="has-text-weight-bold">missing_count </th><td >19,983</td></tr>
          <tr><th class="has-text-weight-bold">missing_ratio </th><td class="has-background-danger-light">0.2 %</td></tr>
          <tr><th class="has-text-weight-bold">row_count     </th><td>12,978,619</td></tr>
        </table>
      </div>
      <div class="column">
        <div><canvas id="e6537ea7-1f58-4ba7-ad17-769ce9160ab7"></canvas></div>
        <!-- Include Chart.js library -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
          (function() {
            new Chart(
              document.getElementById('e6537ea7-1f58-4ba7-ad17-769ce9160ab7'),
              {
                type: 'bar',
                data: {
                  labels: ["[0.5, 2.25[","[2.25, 4[","[4, 5.75[","[5.75, 7.5[","[7.5, 9.25[","[9.25, 11[","[11, 12.75[","[12.75, 14.5[","[14.5, 16.25[","[16.25, 18]"],
                  datasets: [{
                    label: 'value_count',
                    data: [84161,186850,976204,5885362,5132205,668553,24143,950,126,82],
                    borderColor: 'rgb(64, 81, 181)',
                    backgroundColor: 'rgb(64, 81, 181)',
                  }]
                },
                options: {}
              }
            );
          })();
        </script>
      </div>
    </div>
  </div>
</div>

```

Here is what I expected:
![image](https://github.com/unytics/bigfunctions/assets/25187424/4957d9ae-0086-477e-91cf-3f2862d1fad4)

**Comment by unytics** [comment]
Hi @amirali-shfz. 

I am very pleased you created this issue. 

When I started bigfunctions more than a year ago I designed a bookmarlet (kind of chrome extension but easier) to render the html result of a function in BigQuery console such as this screenshot. 

But:

- BigQuery UI changed, then the bookmarklet did not work any more
- Google released dataplex data profiling and then I was not sure that this function is still needed anymore.
- More importantly, I came to think that functions should not create html, only data. If we want to render data in a UI we should use another tool. 

So I gave up html rendering in BigQuery console.

Until now. 


I'd be please to have your feedback:

1. Is this function really interesting to you? Why not use dataplex data profiling?
2. Would you use if it were accessible not from bigquery console but from another website such as https://cloud.unytics.io ? 
3. Would you be ready to authenticate with google on that website so that it can use your BigQuery credentials to perform the query for you before displaying the rendered html?

**Comment by amirali-shfz** [comment]
1. I am new to dealing with data directly, and currently dealing with some very unclean tables. It'd allow me to understand a column quickly without doing multiple queries to check fill-rate, seeing some samples, etc. Honestly I'm likely butchering this function by calling it on a string column... Looking at dataplex, it seems to answer this issue actually nice pointer! I'll look into that.
2. It would be fine if there was a link that I could click and see the graph elsewhere. Note that this is in work context and I'd have to ensure the security of my actions are aligned with company policy.
3. Likely not for a work place use-case. I'd much rather get an html I could render myself

(btw awesome project I'll have to say)

**Comment by unytics** [comment]
Thanks @amirali-shfz for your answers. Very insightful. 

**A. It seems not possible to render html with charts in BigQuery console anymore** 
I tried to make my bookmarlet work again, but it seems that Google secured its page and I am not able to load external javascript anymore *(I get the error "This document requires 'TrustedScriptURL' assignment.")*. Thus I am not able to load chart.js for charting any more. 

**B. Sending to cloud.unyics.io the result of the function**
I understand that exposing your BigQuery credentials to cloud.unytics.io so that cloud.unytics.io make the queries for you is not safe enough for a work place. But sending the computed statistics in json to cloud.unytics.io is much preferable as you would have more control on what you send to cloud.unytics.io. Correct?

So one way to handle this would be:

1. Run `call compute_table_statistics('project.dataset.table')
2. Run `call send_bigfuntion_result_to_unytics()`. 
3. This remote function then stores the json + the fact that it is owned by your email in a unytics database.
4. You can then go to cloud.unytics.io, sign in with Google Sign In (cloud.unytics only see your email) and then you can see the rendered html. You can also delete the json from here.

What do you think? Would it be ok for you?

**Comment by unytics** [comment]
**Hi @amirali-shfz I have good news!**

**I spent my evening on it and realized that it is actually _still_ possible to create a bookmarklet**. 
(Unlike what I thought TrustedScriptURL stuff does not prevent to load external scripts, we just need to declare them safe). 

This link <a href="javascript:(function()%7Blet%20isChartJsLoaded%20%3D%20false%3B%0A%0A%0Aconst%20escapeHTML%20%3D%20function(html)%20%7B%0A%20%20if(!trustedTypes)%20%7B%0A%20%20%20%20return%20html%3B%0A%20%20%7D%0A%20%20const%20policy%20%3D%20trustedTypes.createPolicy(%22forceInner%22%2C%20%7BcreateHTML%3A%20(to_escape)%20%3D%3E%20to_escape%7D)%3B%0A%20%20return%20policy.createHTML(html)%3B%0A%7D%3B%0A%0A%0Aconst%20escapeScript%20%3D%20function(script)%20%7B%0A%20%20if(!trustedTypes)%20%7B%0A%20%20%20%20return%20script%3B%0A%20%20%7D%0A%20%20const%20policy%20%3D%20trustedTypes.createPolicy(%22forceInner%22%2C%20%7BcreateScript%3A%20(to_escape)%20%3D%3E%20to_escape%7D)%3B%0A%20%20return%20policy.createScript(script)%3B%0A%7D%3B%0A%0A%0Aconst%20setInnerHTML%20%3D%20function(elm%2C%20html)%20%7B%0A%20%20elm.innerHTML%20%3D%20escapeHTML(html)%3B%0A%20%20Array.from(elm.querySelectorAll('script')).forEach(%20oldScript%20%3D%3E%20%7B%0A%20%20%20%20%20%20const%20newScript%20%3D%20document.createElement('script')%3B%0A%20%20%20%20%20%20Array.from(oldScript.attributes).forEach(%20attr%20%3D%3E%20newScript.setAttribute(attr.name%2C%20attr.value)%20)%3B%0A%20%20%20%20%20%20newScript.text%20%3D%20escapeScript(oldScript.innerHTML)%3B%0A%20%20%20%20%20%20oldScript.parentNode.replaceChild(newScript%2C%20oldScript)%3B%0A%20%20%7D)%3B%0A%7D%3B%0A%0A%0Aconst%20run%20%3D%20async%20function()%20%7B%0A%20%20if%20(!isChartJsLoaded)%20%7B%0A%20%20%20%20return%3B%0A%20%20%7D%0A%20%20const%20results_table_container%20%3D%20document.querySelector('bq-tab-content%3Anot(.cfc-hidden)%20bq-results-table')%3B%0A%20%20if%20(!results_table_container)%20%7B%0A%20%20%20%20return%3B%0A%20%20%7D%0A%20%20const%20cells%20%3D%20results_table_container.querySelectorAll('td%20div%3Anot(.cfc-flex-container)')%3B%0A%20%20if%20(cells.length%20!%3D%3D%201)%20%7B%0A%20%20%20%20return%3B%0A%20%20%7D%0A%20%20const%20cell%20%3D%20cells%5B0%5D%3B%0A%20%20const%20content%20%3D%20cell.innerText%3B%0A%20%20if%20(!content.startsWith(%22%3Chtml%22))%20%7B%0A%20%20%20%20return%3B%0A%20%20%7D%0A%20%20if%20(content.endsWith(%22...%22))%20%7B%0A%20%20%20%20cell.nextElementSibling.firstElementChild.click()%3B%0A%20%20%20%20return%3B%0A%20%20%7D%0A%20%20const%20html%20%3D%20%60%3Csection%20class%3D%22section%22%3E%24%7Bcontent%7D%3C%2Fsection%3E%60%0A%20%20setInnerHTML(results_table_container%2C%20html)%3B%0A%7D%3B%0A%0A%0Aconst%20loadBulmaCss%20%3D%20function()%20%7B%0A%20%20const%20bulma%20%3D%20document.createElement('link')%3B%0A%20%20bulma.setAttribute('rel'%2C%20'stylesheet')%3B%0A%20%20bulma.setAttribute('href'%2C%20'https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2Fbulma%400.9.4%2Fcss%2Fbulma.min.css')%3B%0A%20%20document.head.appendChild(bulma)%3B%0A%7D%3B%0A%0A%0Aconst%20loadChartjs%20%3D%20function()%20%7B%0A%20%20fetch('https%3A%2F%2Fcdnjs.cloudflare.com%2Fajax%2Flibs%2FChart.js%2F3.9.1%2Fchart.min.js')%0A%20%20.then((response)%20%3D%3E%20response.text())%0A%20%20.then((text)%20%3D%3E%20%7B%0A%20%20%20%20const%20script%20%3D%20document.createElement('script')%3B%0A%20%20%20%20script.text%20%3D%20escapeScript(text)%3B%0A%20%20%20%20document.head.appendChild(script)%3B%0A%20%20%20%20isChartJsLoaded%20%3D%20true%3B%0A%20%20%7D)%3B%0A%7D%3B%0A%0A%0A%0A%0AloadBulmaCss()%3B%0AloadChartjs()%3B%0AsetInterval(run%2C%20100)%3B%7D)()%3B">bigfunctions</a> can be installed as a bookmarklet (I'll show you how in next comment).


Once installed, 

- Go to BigQuery Console
- Click on the bookmark
- Run the following query 
- and see the magic happens!


```
call bigfunctions.eu.explore_column("bigfunctions.eu.natality.weight_pounds");
select '<html>' || html || '</html>' from bigfunction_result;
```



Does it work for you? 

(there still are some adjusments to do but I'd be glad to check it works on your side already).

**Comment by unytics** [comment]
**Hi @amirali-shfz. It works!**

The documentation is displayed on each function.

For example [here](https://unytics.io/bigfunctions/bigfunctions/#explore_column) for `explore_column`

Let me know if it works for you and I'll close this issue.

**Comment by amirali-shfz** [comment]
This works for me! This is awesome man! Thanks for fixing this up, super cool project.
