### ISSUE TITLE
[bug]: `bigfunctions.eu.translate`: it does not work

### ISSUE THREAD

**Issue by flo-pritzy** [unytics/bigfunctions#134]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

I can't use this bigfunction in big query. I try the example : select bigfunctions.eu.translate("Salut 👋 Florian. Merci d'avoir contribué !", 'en') as translated_text 
and I have this bug : 
Received response code 404 from endpoint https://bf-translate-ccbxjzt67q-ew.a.run.app with response <html><head> <meta http-equiv="content-type" content="text/html;charset=utf-8">

**Comment by unytics** [comment]
Thanks @flo-pritzy for opening this issue. I’ll have a look this afternoon.

**Comment by unytics** [comment]
Hi @flo-pritzy. 

I think it is corrected now.

Can you confirm me that it's work for you now?

Thanks

**Comment by unytics** [comment]
it is good to me. 
Don't hesitate to re-open if you encounter new issues
