### ISSUE TITLE
[new]: `refresh_tableau(obj_title_to_refresh)`

### ISSUE THREAD

**Issue by AntoineGiraud** [unytics/bigfunctions#135]
### Check the idea has not already been suggested

- [X] I could not find my idea in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Anew-bigfunction)

### Edit the title above with self-explanatory function name and argument names

- [X] The function name and the argument names I entered in the title above seems self explanatory to me.

### BigFunction Description as it would appear in the documentation

refresh a tableau datasource/workbook via it's REST API by giving the object full title
  the python script will :
  - [login](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_auth.htm) to tableau via the secret `tableau_credentials_json` stored/configured in GCP
  - [search](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_filtering_and_sorting.htm) for a datasource/workbook with the given title to fetch it's UID
  - launch a [refresh](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_data_sources.htm#update_data_source_now), if accepted will return the api call json content
  - logout
  
The GCP **secret** `tableau_credentials_json` : 
  JSON comportant les credentials tableau (Personnal Access Token or user/pswd)
ainsi que le nom du serveur & la [version d'API](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_concepts_versions.htm)
```json
{
    "server_name":"eu-west-1a.online.tableau.com",
    "api_version":"3.21",
    "credentials": {
          "personalAccessTokenName": "mon_token_xxx",
          "personalAccessTokenSecret": "xxx",
          "site": {"contentUrl": "monsitetableau" }
    }
}
```

### Examples of (arguments, expected output) as they would appear in the documentation

- obj_title_to_refresh="Pilotage vol. de leads" --> `{'job': {'extractRefreshJob': {'workbook': {'id': '25c6ab67-fb6b-4357-be96-1d4fee23d479', 'name': 'Pilotage vol. de leads'}}, 'id': 
'2e6fa29e-476e-46b1-8653-deeeccddb0ea', 'mode': 'Asynchronous', 'type': 'RefreshExtract', 'createdAt': '2024-02-06T15:16:11Z'}}`
- obj_title_to_refresh="titre rapport inconnu" --> `not found: titre rapport inconnu`

**Comment by unytics** [comment]
Hi @AntoineGiraud 

I didn't realize you attached some code from your repo in this issue. 

Could you create the merge request from your branch to unytics repo?

Then I merge it, do some eventual small adjustments and deploy it. I'll show you the small changes I made. 

What do you think?

**Comment by unytics** [comment]
merged! 
Thanks @AntoineGiraud  🥇
