### ISSUE TITLE
[bug]: `send_email`: it does not work - Authenticated user is not authorized to send mail

### ISSUE THREAD

**Issue by fcerratos** [unytics/bigfunctions#137]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

Hello, today I try use the function and return this error. 
I tested in my personal machine.
![image](https://github.com/unytics/bigfunctions/assets/91292648/25f1c665-b593-49a7-a054-5d84255c6a04)

**Comment by unytics** [comment]
Hi. 

Thanks for creating the issue.

I had some trouble with my debit card on sendgrid.
It should now be solved.

Can you confirm me it is ok?

Thanks
And sorry for the inconvenience

**Comment by fcerratos** [comment]
Hi,
Solved.
Thanks
