### ISSUE TITLE
[bug]: `is_email_valid`: Wrong for glow.sch.uk domain

### ISSUE THREAD

**Issue by jimmymaise** [unytics/bigfunctions#146]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

select bigfunctions.is_email_valid('name@glow.sch.uk') return false but it should be true

**Comment by unytics** [comment]
Hi @jimmymaise !

Thanks a LOT for opening this issue. 🙌 

I just fixed it with [this commit](https://github.com/unytics/bigfunctions/commit/c35e457fc7fcb24d0ef3c162a4b36bd86bf22543) and redeployed the function.

I assume it is ok and I close the issue.
If it is not, please re-open it. 

thanks
