### ISSUE TITLE
[bug]: prophet: Does not work as expected.

### ISSUE THREAD

**Issue by TFMV** [unytics/bigfunctions#150]
### Check the bug has not already been reported

- [x] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

When attempting to invoke the prophet function, I received the following error when using the provided example:

Number of arguments does not match for function bigfunctions.us.prophet. Supported signature: bigfunctions.us.prophet(JSON, FLOAT64, JSON) at [1:8]

After some experimentation, I was able to get a working example:

WITH sample_data AS (
  SELECT 
    TO_JSON(ARRAY<STRUCT<ds STRING, y FLOAT64>>[
      ('2020-01-01', 1.0),
      ('2020-01-02', 2.0),
      ('2020-01-03', 3.0)
    ]) AS records,
    CAST(3 AS FLOAT64) AS periods,
    TO_JSON(STRUCT<daily_seasonality BOOL, yearly_seasonality BOOL>(TRUE, TRUE)) AS kwargs
)

SELECT 
  `bigfunctions.us.prophet`(
    records,
    periods,
    kwargs
  ) AS forecasted_records
FROM 
  sample_data;

**Comment by unytics** [comment]
Fixed. 
Thanks for reporting.
