### ISSUE TITLE
[bug]: `faker`: Many functions (random_int, boolean...) does not work in BigQuery

### ISSUE THREAD

**Issue by florian-guily** [unytics/bigfunctions#154]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

Many faker functions does not work natively in BigQuery. Seems like every functions that outputs a different type than STRING breaks when used in select statement in BigQuery such as:
`SELECT bigfunctions.eu.faker("boolean", Null)` raising the following error `Failed to decode JSON value true in replies to SQL type STRING.`

You can also try with random_int or unix_time. Maybe i'm using it wrong but nothing indicates how to use it differently.

**Comment by unytics** [comment]
Thanks for opening this issue @florian-guily. 
Great one.

I [fixed it](https://github.com/unytics/bigfunctions/commit/913e0b8198ac6c098e9bf9f999c9af5d7b6aad84) by converting the output to string before returning it.

(Better would be to return a boolean but unfortunately remote function can return only one type). 

It is deployed. 

![image](https://github.com/user-attachments/assets/adfed735-c5b1-4cb0-bb2e-8e57e4270ebe)
