### ISSUE TITLE
[new]: `array_z_scores(arr)`

### ISSUE THREAD

**Issue by julienawonga** [unytics/bigfunctions#155]
### Check the idea has not already been suggested

- [X] I could not find my idea in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Anew-bigfunction)

### Edit the title above with self-explanatory function name and argument names

- [X] The function name and the argument names I entered in the title above seems self explanatory to me.

### BigFunction Description as it would appear in the documentation

Returns an array of z-scores, which are standardized values showing how many standard deviations each element is from the mean.

### Examples of (arguments, expected output) as they would appear in the documentation

- arr=[1, 2, 3, 4, 5] --> [−1.414,−0.707,0,0.707,1.414]

**Comment by unytics** [comment]
Function has been deployed.

Here is the [doc](https://unytics.io/bigfunctions/bigfunctions/z_scores/)

Thanks for your contribution @julienawonga @AxelThevenot
