### ISSUE TITLE
[improve]: `load_file`: add schemaless option to load file in raw format

### ISSUE THREAD

**Issue by lideke** [unytics/bigfunctions#171]
### Check your idea has not already been reported

- [X] I could not find the idea in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short idea description in title above

- [X] I wrote the correct function name and a short idea description in the title above

### Tell us everything

The goal of this feature is to push any data into BiQuery without schema error. 

Input, json newline file : 
```json
{"id": 1, "name":"jean", "age": 10}
{"id": 2, "name":"legend", "age": 20}
```

output in bigquery :
| _extracted_at |  raw_data |
|---|---|
|2024-05-13 19:59:00 UTC |  {"id": 1, "name":"jean", "age": 10}|
|2024-05-13 19:59:00 UTC |  {"id": 2, "name":"legend", "age": 20}|

**Comment by AntoineGiraud** [comment]
Hi @lideke,

If really you want bare text / json ...
without the struct / record

here are some options :
* you can explicitely cast some columns as json (so that it doesn't infer a schema / record)
* add a `"records":false` option ... and maybe ... cast it as text

```sql
-- BigQuery
call bigfunctions.eu.load_file(
  'https://geo.api.gouv.fr/departements?fields=nom,code,codeRegion,region', 
  'json', 'your_project.your_dataset.dim_french_departements',
  '{"records":false, "columns":{"json":"text"}}'
);

select * from your_project.your_dataset.dim_french_departements;
```

![image](https://github.com/user-attachments/assets/06a77122-03d9-4730-9d0c-1f8f28197e07)

**Comment by AntoineGiraud** [comment]
I let you play with those args and come back to us ? :)

Don't hesitate to play with [duckdb json options](https://duckdb.org/docs/data/json/overview.html) before trying running the load_file BigFunction :)

```sql
-- DuckDB 🦆
FROM read_json(
	'https://geo.api.gouv.fr/departements?fields=nom,code,codeRegion,region',
	records=FALSE, columns={json:json}
);
```
