### ISSUE TITLE
[new] `deduplicate_rows(query_or_table_or_view)`

### ISSUE THREAD

**Issue by unytics** [unytics/bigfunctions#27]
returns the table but with rows deduplicated

**Comment by shivam221098** [comment]
Is this can be a procedure? I think that matches the use cases.

**Comment by unytics** [comment]
yep. It must be a procedure as (as far as I know):

- we cannot pass a table object to a routine yet, only its name. 
- then we must use `execute immediate` to make queries upon the input table
- only procedures can use `execute immediate`
