### ISSUE TITLE
[bug]: `remove_strings`: it does not work

### ISSUE THREAD

**Issue by GaylorBrunner22** [unytics/bigfunctions#58]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

The function remove_strings does not work with some strings : 
When used to remove brackets, it does not do it. 

To be precise, here is what happens : 
`select bigfunctions.eu.remove_strings('test_-test test()', ['_', '-',' ','(',')']) as cleaned_string`
will result in : 
testtesttest()
And  
`select bigfunctions.eu.remove_strings('test_-test test()', ['(',')','_', '-',' ']) as cleaned_string`
will result in : 
test_-test test()

**Comment by unytics** [comment]
Congrats @shivam221098.
Great first contribution. 👏
