### ISSUE TITLE
[new]: `json2xml(json)`

### ISSUE THREAD

**Issue by shivam221098** [unytics/bigfunctions#69]
### Check the idea has not already been suggested

- [X] I could not find my idea in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Anew-bigfunction)

### Edit the title above with self-explanatory function name and argument names

- [X] The function name and the argument names I entered in the title above seems self explanatory to me.

### BigFunction Description as it would appear in the documentation

Takes in JSON as a string and returns parsed XML from JSON.

### Examples of (arguments, expected output) as they would appear in the documentation

```
const json = JSON.stringify({
    "breakfast_menu": {
        "food": [
            {
                "name": "Belgian Waffles",
                "price": "$5.95",
                "description": "Two of our famous Belgian Waffles with plenty of real maple syrup",
                "calories": 650
            },
            {
                "name": "Strawberry Belgian Waffles",
                "price": "$7.95",
                "description": "Light Belgian waffles covered with strawberries and whipped cream",
                "calories": 900
            },
            {
                "name": "Berry-Berry Belgian Waffles",
                "price": "$8.95",
                "description": "Light Belgian waffles covered with an assortment of fresh berries and whipped cream",
                "calories": 900
            },
            {
                "name": "French Toast",
                "price": "$4.50",
                "description": "Thick slices made from our homemade sourdough bread",
                "calories": 600
            },
            {
                "name": "Homestyle Breakfast",
                "price": "$6.95",
                "description": "Two eggs, bacon or sausage, toast, and our ever-popular hash browns",
                "calories": 950
            }
        ]
    }
})
```
`json2xml(json) -> "<breakfast_menu><food><name>Belgian Waffles</name><price>$5.95</price><description>Two of our famous Belgian Waffles with plenty of real maple syrup</description><calories>650</calories></food><food><name>Strawberry Belgian Waffles</name><price>$7.95</price><description>Light Belgian waffles covered with strawberries and whipped cream</description><calories>900</calories></food><food><name>Berry-Berry Belgian Waffles</name><price>$8.95</price><description>Light Belgian waffles covered with an assortment of fresh berries and whipped cream</description><calories>900</calories></food><food><name>French Toast</name><price>$4.50</price><description>Thick slices made from our homemade sourdough bread</description><calories>600</calories></food><food><name>Homestyle Breakfast</name><price>$6.95</price><description>Two eggs, bacon or sausage, toast, and our ever-popular hash browns</description><calories>950</calories></food></breakfast_menu>"
`

**Comment by unytics** [comment]
Great job @shivam221098 ! 👏
