### ISSUE TITLE
[Issue] the function `is_email_valid` is too permissive

### ISSUE THREAD

**Issue by mickaelandrieu** [unytics/bigfunctions#8]
Hi everyone!

Here a few cases, I've tested:

- *@hotmail.fr => TRUE
- !!!!!!@gmail.com => TRUE
- ***12@hotmail.fr => TRUE

To be honest, I don't see how we can solve this. This should be done at application level __before__ being stored in BQ.

**Comment by unytics** [comment]
Hi @mickaelandrieu, 

According to Wikipedia, these emails seem valid, no? 
At least, `*` and `!` seem valid characters in the first part of the email.

https://en.wikipedia.org/wiki/Email_address#Local-part

Or maybe it is forbidden to have only these characters?
