### ISSUE TITLE
[bug]: a statement isn't working with new procedure

### ISSUE THREAD

**Issue by shivam221098** [unytics/bigfunctions#87]
### Check the bug has not already been reported

- [X] I could not find the bug in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Abug-bigfunction)

### Edit `function_name` and the short error description in title above

- [X] I wrote the correct function name and a short error description in the title above

### What happened and what did you expect?

When I created a new procedure and deployed it into my project. I see there is an insert statement that is concatenated in each new procedure, but my procedure is unable to find the logs table.

![image](https://user-images.githubusercontent.com/56783600/235309982-8d995627-c926-4629-bbdb-912d8bc3ae58.png)

**Comment by unytics** [comment]
solved.

I simply removed logging in stored procedure.


I wanted to add logging for stored procedures so that a user could get logs of stored procedures execution with `bigfun logs my_stored_procedure`. But the disadvantages of logging outweigh the advantages for now.
