### ISSUE TITLE
[new]: `send_teams_message(message, webhook_url)`

### ISSUE THREAD

**Issue by unytics** [unytics/bigfunctions#93]
### Check the idea has not already been suggested

- [X] I could not find my idea in [existing issues](https://github.com/unytics/bigfunctions/issues?q=is%3Aissue+is%3Aopen+label%3Anew-bigfunction)

### Edit the title above with self-explanatory function name and argument names

- [X] The function name and the argument names I entered in the title above seems self explanatory to me.

### BigFunction Description as it would appear in the documentation

duplicate send_slack_message.yaml. 
Change doc and assertion in code. 

Teams incoming webhook doc: 
https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=javascript

### Examples of (arguments, expected output) as they would appear in the documentation

-

**Comment by unytics** [comment]
Deployed in bigfunctions.eu dataset. Can you check that it works correctly @batou9150 ?

**Comment by batou9150** [comment]
@unytics it works 😉 

<img width="766" alt="Screenshot 2023-05-31 at 08 01 37" src="https://github.com/unytics/bigfunctions/assets/5543433/4c31edb4-b376-4f60-ad93-1b26a4135f2f">

Result:
<img width="547" alt="Screenshot 2023-05-31 at 08 01 53" src="https://github.com/unytics/bigfunctions/assets/5543433/5b91f98b-1bf1-4148-a6b2-bf0284922d7d">
